eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka

spring:
  application:
    name:  gateway
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=X-Gateway, true
      routes:
        - id: SpringCloud
          uri: http://localhost:8000/
          predicates:
            - Path=/client/
            - Path=/trip/
          filters:
            - SetPath=/dummy/{segment}
        - id: eureka-client
          uri: lb://eureka-client1
          predicates:
            - Path=/eureka/**
          filters:
            - RewritePath=/eureka/(?<segment>.*), /$\{segment}
        - id: SpringCloudFRONT
          uri: http://localhost:8081
          predicates:
            - Path=/client/
            - Path=/trip/
          filters:
            - AddRequestHeader=X-Request-PROFE, Hola
            - PrefixPath=/dummy
            - RemoveRequestHeader=X-Request-Foo
